library(Seurat)
# get gamm metadata
setwd("/w5home/bmoore/scRNAseq/GAMM/GAMM_S2/output_20230830_155530/")
gamm <- readRDS(file = "seurat_obj_labeled.rds")
colnames(gamm@meta.data)
unique(gamm@active.ident)
Idents(gamm)
gamm$CellType <- Idents(gamm)
saveRDS(gamm, file = "GAMM_S2_clabeled-clusters_0.5.rds")
gamm.metadata<- as.data.frame(gamm@meta.data)
write.table(gamm.metadata, file = "gamm_manual_annot_metadata_c0.5.txt", sep="\t", quote=F, row.names = T)
colnames(gamm@assays$RNA@data)
