---
title: "subset_data_for_positively_expressed_cells"
author: "Beth Moore"
date: "2024-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(patchwork)
library(purrr)
library(jsonlite)
library(rmarkdown)
library(reticulate)
library(multtest)
library(metap)
library(harmony)
library(SeuratWrappers)
library(ggplot2)
library(scran)
library(clustifyr)
library(SeuratDisk)
use_condaenv("scRNAseq_best")

# set variables
#GIT_DIR <- "/w5home/bmoore/scRNAseq_downstream/"
config <- jsonlite::fromJSON(file.path("./config.json"))
DATA_DIR <- config$subset_seurat$DATA_DIR
SEURAT_OBJ <- config$subset_seurat$SEURAT_OBJ
GENE_LIST <- config$subset_seurat$GENE_LIST
DIM.RED <- config$subset_seurat$DIM.RED
ANNOT <- config$subset_seurat$ANNOT
# set up environment and output
setwd(DATA_DIR)
timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
output <- paste0("output_subset_", timestamp)
dir.create(output, showWarnings = FALSE)
file.copy(paste0("config.json"), file.path(output, "config.json"))
output <- paste0(output, "/")
config <- jsonlite::fromJSON(file.path(output, "config.json"))
source(paste0("src/sc_pipeline_functions.R"))
```
```{r load_data}
seurat.obj <- readRDS(file = SEURAT_OBJ)
seurat.obj
```
# subset for positively expressed genelist
```{r get_cells}
new.obj <- GetAssayData(object = seurat.obj, layer = "data")[GENE_LIST,]>0
```
```{r subset}
#get the required cells
df <- as.data.frame(new.obj)
# get cells that are true
cellstokeep <- which(apply(df, 2, any))
#subset the required cells
seurat.obj_subset <- subset(seurat.obj, cells = cellstokeep)
seurat.obj_subset
```
```{r plot}
p1 <- DimPlot(seurat.obj_subset, reduction = DIM.RED, label = TRUE, 
        pt.size = 0.5, group.by = ANNOT)
p2 <- DimPlot(seurat.obj, reduction = DIM.RED, label = TRUE, 
        pt.size = 0.5, group.by = ANNOT)
p3 <- DimPlot(seurat.obj_subset, reduction = DIM.RED, 
        pt.size = 0.5, group.by = "orig.ident")
p4 <- DimPlot(seurat.obj_subset, reduction = DIM.RED, label = TRUE, 
        pt.size = 0.5, group.by = "seurat_clusters")
p5 <- FeaturePlot(seurat.obj_subset, features = GENE_LIST, ncol = length(GENE_LIST),
                           pt.size = 0.5, reduction = DIM.RED) &
                           scale_color_viridis(option="B")
combined_plot <- ((p1 | p2) / (p3 | p4) / p5) + plot_layout(width = c(2, 2, 2),
                                                      heights = c(1, 1, 1))
pdf(file = paste0(output,"seurat_subset.pdf"), width = 8, height = 8)
    print(combined_plot)
dev.off()
```
```{r save}
saveRDS(seurat.obj_subset, file= paste0(output,"seurat.obj_subset.rds"))
```
# save session info
```{r sessioninfo}
writeLines(capture.output(sessionInfo()), paste0(output,"sessionInfo.txt"))
```