# load libraries
```{r install}
## install
# install.packages("reticulate")
# install.packages("devtools")
# Install the CASSIA package
library(devtools)
devtools::install_github("ElliotXie/CASSIA/CASSIA_R")
```
```{r libraries}
# load libraries
library(reticulate)
library(devtools)
library(CASSIA)
library(Seurat)
library("dplyr")
reticulate::use_python("/w5home/bmoore/miniconda3/envs/cassia_env/bin/python", required = T)
library(stringr)
```
```{r}
setup_cassia_env()
```
```{r api}
# For OpenAI
setLLMApiKey("api_key", provider = "openai", persist = TRUE)
```
# read in
```{r readin}
getwd()
setwd("/w5home/bmoore/scRNAseq/GAMM/GAMM_S2/output_20230830_155530/")
seurat.obj <- readRDS("GAMM_S2_clabeled-clusters_0.5.rds")
print(seurat.obj)
colnames(seurat.obj@meta.data)
# table(seurat.obj$cell_type)
```
# set idents
```{r subset}
# set idents
Idents(object = seurat.obj) <- "seurat_clusters"
# seurat.sub <- subset(x = seurat.obj, idents = c("erythrocyte", "monocyte"))
```
# find all markers for each cluster/celltype
```{r findmarkers}
# find markers
all.markers <- FindAllMarkers(object = seurat.obj)
head(all.markers)
all.markers <- as.data.frame(all.markers)
# all.markers.sub <- subset(all.markers, cluster %in% c("erythrocyte"))
genelist <- row.names(all.markers)
write.csv(all.markers, file = "markers_celltypes_all.csv", row.names = FALSE)
```
# make sure gene symbols are used
```{r readin_geneid}
# gene_symbols_df <- read.csv(file = "/w5home/bmoore/genomes/human_genome_38/ensemble_humanGR38_geneIDs.txt",
#                     header =TRUE, sep = "\t")
gene_symbols_df <- read.csv(
  file = "/w5home/bmoore/scRNAseq/GAMM/human_data/reh_cellrep_2020/Human_Pig_Biomart_Filtered_mod.txt",
  header = TRUE, sep = "\t"
)
print(head(gene_symbols_df))
gene_symbols_df$pig.gene.name <- toupper(gene_symbols_df$pig.gene.name)
```
# merge with marker list
```{r}
markers_merge <- merge(all.markers, gene_symbols_df,
  by.x = "gene", by.y = "pig.gene.name",
  all = FALSE
) # all.x = TRUE)
print(head(markers_merge))
```
# rename columns and drop
```{r}
markers_merge$pig_gene <- markers_merge$gene
markers_merge$gene <- markers_merge$human.gene.name
colnames(markers_merge)
```
```{r}
markers_merge <- markers_merge[, 1:7]
head(markers_merge)
# get unique
markers_merge_unique <- distinct(markers_merge)
# markers.sub <- subset(markers_merge_unique, cluster %in% c("erythrocyte"))
nrow(markers_merge_unique)
nrow(markers_merge)
```
# run default cassia
```{r cassia}
runCASSIA_pipeline(
  output_file_name = "pigIPS_day120_res05",
  tissue = "retina",
  species = "pig",
  marker = markers_merge_unique,
  max_workers = 4,
  annotation_model = "gpt-5.1",
  annotation_provider = "openai",
  score_model = "gpt-5.1",
  score_provider = "openai",
  annotationboost_model = "gpt-5.1",
  annotationboost_provider = "openai"
)
```
# add cassia back into seurat object
```{r}
## doesnt work- email cassia
seurat_obj <- add_cassia_to_seurat(
  seurat_obj = seurat.obj,
  cassia_results_path = "/w5home/bmoore/scRNAseq/GAMM/GAMM_S2/output_20230830_155530/CASSIA_Pipeline_retina_pig_20260318_134520/03_csv_files/pigIPS_day120_res05_FINAL_RESULTS.csv",
  cluster_col = "seurat_clusters",
  cassia_cluster_col = "Cluster ID",
  prefix = "Cassia_0.5_res_"
)
```

```{r}
library(qs2)
print("saving object via qs2")
# sham
qs_save(seurat.obj, "GAMM_S1_clabeled-clusters_0.5_cassia.qs2")
# convert to rds
qs_to_rds(
  input_file = "GAMM_S1_clabeled-clusters_0.5_cassia.qs2",
  output_file = "GAMM_S1_clabeled-clusters_0.5_cassia.rds"
)

# saveRDS(seurat.obj, file="GAMM_S1_clabeled-clusters_0.5_cassia.rds")
```

```{r}
library(patchwork)
library(ggplot2)
# plot newly annotated clusters
plot1 <- DimPlot(seurat.obj,
  reduction = "umap", label = TRUE,
  pt.size = 0.5, group.by = "Cassia_0.5_res_merged_grouping_1"
)
plot2 <- DimPlot(seurat.obj,
  reduction = "umap", label = TRUE,
  pt.size = 0.5, group.by = "Cassia_0.5_res_merged_grouping_2"
)
plot3 <- DimPlot(seurat.obj,
  reduction = "umap", label = TRUE,
  pt.size = 0.5, group.by = "Cassia_0.5_res_merged_grouping_3"
)
combined_plot <- (plot1 | plot2 | plot3) + plot_layout(
  width = 3,
  heights = 1
)
pdf(
  file = paste0("Cassia_annot_0.5_res_umap.pdf"),
  width = 8, height = 6
)
print(combined_plot)
dev.off()
```

# get markers from both logFC and expression
```{r}
high_expr_dir <- "/w5home/bmoore/Pierre_sc_zebrafish/output_subset-recluster_20260204_094842/Top50_HighExpr_Genes_all_res0.75/"
high_files <- list.files(path = high_expr_dir, pattern = "Top50_HighExpr_Genes_all_Cluster_\\d+\\.txt$", full.names = TRUE)

# Initialize list to store genes
cluster_genes_list <- list()

# Loop through High Expression files
for (file in high_files) {
  filename <- basename(file)
  # Extract number from "Cluster_X"
  num <- str_extract(filename, "(?<=Cluster_)\\d+")
  cluster_name <- paste0(num)

  data <- read.table(file, header = TRUE)
  genes <- data$Gene[1:25]

  cluster_genes_list[[cluster_name]] <- genes
}

DE_dir <- "/w5home/bmoore/Pierre_sc_zebrafish/output_subset-recluster_20260204_094842/Top100_DE_Genes_all_res0.75/"
de_files <- list.files(path = DE_dir, pattern = "Top100DEgenes_clust_\\d+\\.txt$", full.names = TRUE)

# Loop through DE files and append
for (file in de_files) {
  filename <- basename(file)
  # Extract number from "clust_X"
  num <- str_extract(filename, "(?<=clust_)\\d+")
  cluster_name <- paste0(num)

  data <- read.table(file, header = TRUE)
  # DE genes are row names in this file format
  genes <- rownames(data)

  if (cluster_name %in% names(cluster_genes_list)) {
    # Append and ensure uniqueness
    cluster_genes_list[[cluster_name]] <- unique(c(cluster_genes_list[[cluster_name]], genes))
  } else {
    cluster_genes_list[[cluster_name]] <- genes
  }
}

# Convert to data frame
# Convert zebrafish genes to human genes
for (name in names(cluster_genes_list)) {
  genes <- cluster_genes_list[[name]]
  # Map to human genes
  human_genes <- gene_symbols_df$Human.gene.name[match(toupper(genes), gene_symbols_df$Zebrafish.Gene.name)]
  # Remove NAs and empty strings
  human_genes <- human_genes[!is.na(human_genes) & human_genes != ""]

  cluster_genes_list[[name]] <- unique(human_genes)
}

# Convert to data frame
new_df <- data.frame(
  cluster = names(cluster_genes_list),
  marker_genes = sapply(cluster_genes_list, paste, collapse = ", "),
  stringsAsFactors = FALSE
)

write.csv(new_df, file = "markers2_all_celltypes_0.75.csv", row.names = FALSE)
```

# run cassia again
```{r}
runCASSIA_pipeline(
  output_file_name = "zebrafish_res075_v2",
  tissue = "spinal cord",
  species = "zebrafish",
  marker = new_df,
  max_workers = 4,
  annotation_model = "gpt-4o",
  annotation_provider = "openai",
  score_model = "gpt-4o",
  score_provider = "openai",
  annotationboost_model = "gpt-4o",
  annotationboost_provider = "openai"
)
```
