```{r load_packages}
library(CellChat)
library(patchwork)
library(Seurat)
library(Matrix)
library(NMF)
library(ggalluvial)
library(reticulate)
options(stringsAsFactors = FALSE)
```
```{r load_data}
data_dir <- "/w5home/bmoore/Pierre_sc_zebrafish/"
setwd(data_dir)
filename <- "seurat_mouse_annot_sham.rds"
timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
output <- paste0(data_dir, name,"_cellchat_",timestamp)
print(output)
dir.create(output, mode = "0777", showWarnings = FALSE)
output <- paste0(output, "/")
name <- basename(filename)
seurat_obj <- readRDS(filename)
print(seurat_obj)
```
# make cell chat obj
```{r get_ccobject}
# make cell chat object
cellchat <- createCellChat(object = seurat_obj, 
        group.by = "CellType", assay = "RNA")
print(cellchat)

# Convert dataframe to matrix first, then to sparse matrix
# data.input.matched <- as.matrix(data.input.matched)
# # then convert to sparse matrix
# library(Matrix)
# data.input.matched <- Matrix(data.input.matched, sparse = TRUE)
# # then make cell chat obj from matrix
# cellchat <- createCellChat(object = data.input.matched, meta = meta, group.by = "labels")

```
# set idents
```{r set_ident}
cellchat <- setIdent(cellchat, ident.use = "CellType")
levels(cellchat@idents)
groupSize <- as.numeric(table(cellchat@idents))
print(groupSize)
print(table(cellchat@idents))
```
# get cell chat DB
```{r get_database}
CellChatDB <- CellChatDB.mouse # use CellChatDB.human if running on human data
showDatabaseCategory(CellChatDB)
# Show the structure of the database
dplyr::glimpse(CellChatDB$interaction)
```
# subset DB
```{r subset_db}
# use all CellChatDB except for "Non-protein Signaling" for cell-cell communication analysis
CellChatDB.use <- subsetDB(CellChatDB)
# set the used database in the object
cellchat@DB <- CellChatDB.use
```
# preprocess expr data
```{r preprocess_exp}
# subset the expression data of signaling genes for saving computation cost
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
# set maxSize
oopts <- options(future.globals.maxSize = 2.0 * 1e9) # 2GB
on.exit(options(oopts))
future::plan("multisession", workers = 4) # do parallel
# ID over-expression
print("Identifying over-expressed genes and interactions")
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
```
# compute communication probability
```{r cc_prob}
# compute communication probability
print("compute communication probability")
ptm = Sys.time()
# options: # type set to trimean for fewer interactioins, also control for abundant cell type bias 
cellchat <- computeCommunProb(cellchat, type = "triMean",population.size = TRUE)
# filter few cells 
cellchat <- filterCommunication(cellchat, min.cells = 10)
# extract dfs
df.net <- subsetCommunication(cellchat) # df of inferreed cc communications from ligand/receptors
df.net.p <- subsetCommunication(cellchat, slot.name = "netP") # inferred at signal pathways
# get signifcant pathways
cellchat <- computeCommunProbPathway(cellchat)
execution.time = Sys.time() - ptm
print(paste0("communication porbability computation time: " ,as.numeric(execution.time, units = "mins")))
```
# save
```{r save}
print("saving")
write.table(df.net,file=paste0(output,"cellchat_df_net_ligand-recept.txt"), sep="\t", quote=FALSE)
write.table(df.net.p,file=paste0(output,"cellchat_df_net_signal_paths.txt"), sep="\t", quote=FALSE)
saveRDS(cellchat, file=paste0(output,"cellchat_obj.rds"))

```

```{r}
# read object back in
output <- "/w5home/bmoore/Pierre_sc_zebrafish/seurat_mouse_annot_1wk_cellchat_20250425_093018/"
cellchat <- readRDS(file=paste0(output,"seurat_mouse_annot_1wk_cellchat_obj.rds"))
name <- "seurat_mouse_annot_1wk"
```

```{r aggregate}
# aggregate cell-cell network by summarizing cc-communication probs
print("aggregating cell-cell network")
        ptm = Sys.time()
        cellchat <- aggregateNet(cellchat)
        execution.time = Sys.time() - ptm
print(paste0("aggregaing cell-cell network time: " ,as.numeric(execution.time, units = "secs")))
# write out
df.net.ag <- as.data.frame(cellchat@net$weight)
write.table(df.net.ag, file=paste0(output, name, "_netaggregate_weights.txt"), quote=FALSE, row.names = FALSE)
```

```{r}
# visualize as circle plot
ptm = Sys.time()
groupSize <- as.numeric(table(cellchat@idents))
pdf(file=paste0(output, name,"cc_interactions_celltype_circleplot.pdf"))
par(mfrow = c(1,2), xpd=TRUE)
    netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T,  label.edge= F, title.name = "Number of interactions")
    netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")
dev.off()
```

```{r}
# visualize from each cell group
mat <- cellchat@net$weight
pdf(file=paste0(output, name,"cc_interactions_celltype_circleplot2.pdf"))
par(mfrow = c(3,4), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}
dev.off()
```

```{r}
# Access all the signaling pathways showing significant communications
pathways.show.all <- cellchat@netP$pathways
# check the order of cell identity to set suitable vertex.receiver
levels(cellchat@idents)
vertex.receiver = seq(1,4)
# make pathways folder
path_dir <- paste0(output,"pathway_analysis")
dir.create(path_dir, mode = "0777", showWarnings = FALSE)
path_dir <- paste0(path_dir, "/")
print("doing individual pathway analysis")
# pathway analysis and figures
for (i in 1:length(pathways.show.all)) {
                # Visualize communication network associated with both signaling pathway and individual L-R pairs
                setwd(path_dir)
                print(pathways.show.all[i])
                netVisual(cellchat, signaling = pathways.show.all[i], vertex.receiver = vertex.receiver, 
                        layout = "hierarchy",out.format ="pdf")
                #dev.off()
                # Compute and visualize the contribution of each ligand-receptor pair to the overall signaling pathway
                gg <- netAnalysis_contribution(cellchat, signaling = pathways.show.all[i])
                ggsave(filename=paste0(path_dir, pathways.show.all[i], "_path_L-R_contribution.pdf"), 
                        plot=gg, width = 3, height = 2, units = 'in', dpi = 300)
                #dev.off()
                # aggregate interactions
                pdf(file=paste0(path_dir, "cc_interactions_",pathways.show.all[i],"_circplot.pdf"))
                par(mfrow=c(1,1))
                netVisual_aggregate(cellchat, signaling = pathways.show.all[i], layout = "circle", 
                vertex.weight = groupSize)
                dev.off()
                
                # Heatmap
                p2 <- netVisual_heatmap(cellchat, signaling = pathways.show.all[i], color.heatmap = "Reds")
                pdf(file=paste0(path_dir, "cc_interactions_",pathways.show.all[i],"_heatmap.pdf"))
                par(mfrow=c(1,1))
                print(p2)
                dev.off()
                # extract all sig L-R pairs and related sig genes for a pathway
                pairLR <- extractEnrichedLR(cellchat, signaling = pathways.show.all[i], geneLR.return = FALSE)
                LR.show <- pairLR[1,] # show one ligand-receptor pair
                
                # Circle plot
                pdf(file=paste0(path_dir, "top_L-Rpairs_",pathways.show.all[i],"_signaling.pdf"))
                netVisual_individual(cellchat, signaling = pathways.show.all[i], pairLR.use = LR.show, layout = "circle")
                dev.off()
                # bubble plot with sig interactions for a signaling pathway
                p4 <- netVisual_bubble(cellchat, sources.use = c(6), targets.use = c(4,12), 
                        signaling = pathways.show.all[i], remove.isolate = FALSE)
                pdf(file=paste0(path_dir,"sig_cc_L-Rpairs_",pathways.show.all[i],"_path_bubble_Tcells.pdf"), height = 11, width = 8.5)
                print(p4)
                dev.off()
                p5 <- netVisual_bubble(cellchat, sources.use = c(8), targets.use = c(6,5,3,7,13,14), 
                        signaling = pathways.show.all[i], remove.isolate = FALSE)
                pdf(file=paste0(path_dir,"sig_cc_L-Rpairs_",pathways.show.all[i],"_path_bubble_fibroblast.pdf"), height = 11, width = 8.5)
                print(p5)
                dev.off()  
                # plot gene expression for a given pathway
                p6 <- plotGeneExpression(cellchat, signaling = pathways.show.all[i], enriched.only = TRUE, type = "violin")
                pdf(file=paste0(path_dir,pathways.show.all[i],"_path_sig_geneExpr_violin.pdf"))
                print(p6)
                dev.off()
        }
```
```{r}
# load libraries
library(CellChat)
library(patchwork)
library(Seurat)
library(Matrix)
library(NMF)
library(ggalluvial)
library(reticulate)
# read back in
output <- "/w5home/bmoore/Pierre_sc_zebrafish/seurat_mouse_annot_sham.rds_cellchat_20250520_100324/"
cellchat <- readRDS(paste0(output,"cellchat_obj.rds"))
```
```{r}
# name <- "seurat_mouse_annot_4wkNR"
# cell-cell communication mediated by multiple ligand-receptors or signaling pathways
# (1) show all the significant interactions (L-R pairs) from some cell groups 
# (defined by 'sources.use') to other cell groups (defined by 'targets.use')
# bubble plot
setwd(output)
# sig L-R pairs for interaction
p1 <- netVisual_bubble(cellchat, sources.use = c(6), targets.use = c(4,12), remove.isolate = FALSE)
pdf(file=paste0(output, name, "_sig_cc_L-Rpairs_celltypes_bubble_Tcells.pdf"), height = 11, width = 8.5)
print(p1)
dev.off()
# sig L-R pairs for interaction
p2 <- netVisual_bubble(cellchat, sources.use = c(8), targets.use = c(6,5,3,7,13,14), remove.isolate = FALSE)
pdf(file=paste0(output, name, "_sig_cc_L-Rpairs_celltypes_bubble_fibroblasts.pdf"), height = 11, width = 8.5)
print(p2)
dev.off()
# sig L-R pairs for interaction T cells
pdf(file=paste0(output, name, "_sig_cc_L-Rpairs_celltypes_chord_Tcells.pdf"))
netVisual_chord_gene(cellchat, sources.use = c(6), targets.use = c(4,12), lab.cex = 0.5,legend.pos.y = 30)
dev.off()
# receiving
pdf(file=paste0(output, name, "_sig_cc_L-Rpairs_celltypes_chord_Tcells_receive.pdf"))
netVisual_chord_gene(cellchat, sources.use = c(4,12), targets.use = c(6), lab.cex = 0.5,legend.pos.y = 30)
dev.off()
# sig L-R pairs for interaction fibroblasts
pdf(file=paste0(output, name, "_sig_cc_L-Rpairs_celltypes_fibroblasts.pdf"))
netVisual_chord_gene(cellchat, sources.use = c(8), targets.use = c(6,5,3,7,13,14), legend.pos.x = 15)
dev.off()
# receivinb
pdf(file=paste0(output, name, "_sig_cc_L-Rpairs_celltypes_fibroblasts_receive.pdf"))
netVisual_chord_gene(cellchat, sources.use = c(6,5,3,7,13,14), targets.use = c(8), legend.pos.x = 15)
dev.off()
# show all the significant signaling pathways from some cell groups (defined by 'sources.use') to other cell groups (defined by 'targets.use')
pdf(file=paste0(output, name, "_sig_cc_pathways_chord_Tcells.pdf"))
netVisual_chord_gene(cellchat, sources.use = c(6), targets.use = c(4,12), slot.name = "netP", legend.pos.x = 10)
dev.off()
pdf(file=paste0(output, name, "_sig_cc_pathways_chord_fibroblasts.pdf"))
netVisual_chord_gene(cellchat, sources.use = c(8), targets.use = c(6,5,3,7,13,14), slot.name = "netP", legend.pos.x = 10)
dev.off()

```

```{r}
# Systems analysis of cell-cell communication network
# uses graph theory, pattern recognition and manifold learning
# identify dominant senders, receivers, mediators and influencers in the intercellular communication network by computing several network centrality measures for each cell group

print("do net analysis")
        # Systems analysis of cell-cell communication network
        cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways
        # Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups
        ng <- netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 8, 
                height = 2.5, font.size = 10)
        #Visualize dominant senders (sources) and receivers (targets)
        # Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
        gg1 <- netAnalysis_signalingRole_scatter(cellchat)
        # save
        pdf(file=paste0(output, name, "_NetAnalysis_celltype_allpaths_2Dmap.pdf"))
           print(gg1)
        dev.off()
        # Identify signals contributing the most to outgoing or incoming signaling of certain cell groups
        # Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
        ht1 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing")
        ht2 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "incoming")
        pdf(file=paste0(output, name, "_NetAnalysis_allcelltype_allpaths_heatmap.pdf")) #, width=10,height=10
        print(ht1 + ht2)
        dev.off()
```

```{r}
# global communication patterns
# For outgoing (or incoming) patterns, the cell group pattern matrix W outputted from the matrix factorization of outgoing (or incoming) cell-cell communication probability indicates how these cell groups coordinate to send (or receive) signals and the signaling pathway pattern matrix H indicates how these signaling pathways work together to send (or receive) signals.

# global communication patterns
        print("global communication patterns, running select k to get number of patterns")
        # run selectK to infer the number of patterns.
        po <- selectK(cellchat, pattern = "outgoing")
        pdf(file=paste0(output, name, "_pattern_selection_outgoing.pdf"))
        print(po)
        dev.off()
         # incoming
        pi <- selectK(cellchat, pattern = "incoming")
        pdf(file=paste0(output, name, "_pattern_selection_incoming.pdf"))
        print(pi)
        dev.off()
        # where do Cophenetic and Silhouette values begin to drop suddenly?
 
```

```{r}
name <- "seurat_mouse_annot_sham"
nPatternsOut = 3
cellchat <- identifyCommunicationPatterns(cellchat, pattern = "outgoing", k = nPatternsOut)
# river plot
pr <- netAnalysis_river(cellchat, pattern = "outgoing")
pdf(file=paste0(output, name, "_global_cc_patterns_outgoing.pdf"))
print(pr)
dev.off()
# dot plot
pd <- netAnalysis_dot(cellchat, pattern = "outgoing")
pdf(file=paste0(output, name, "_global_cc_patterns_outgoing_dotplot.pdf"))
print(pd)
dev.off()

# set patterns for incoming
nPatternsIn = 3
cellchat <- identifyCommunicationPatterns(cellchat, pattern = "incoming", k = nPatternsIn)
# river plot
pr2 <- netAnalysis_river(cellchat, pattern = "incoming")
pdf(file=paste0(output, name, "_global_cc_patterns_incoming.pdf"))
print(pr2)
dev.off()
# dot plot
pd2 <- netAnalysis_dot(cellchat, pattern = "incoming")
pdf(file=paste0(output, name, "_global_cc_patterns_incoming_dotplot.pdf"))
print(pd2)
dev.off()
```

```{r}
# save then read back in
#saveRDS(cellchat, file=paste0(output,"cellchat_obj.rds"))
library(CellChat)
library(patchwork)
library(Seurat)
library(Matrix)
library(NMF)
library(ggalluvial)
library(reticulate)
output <- "/w5home/bmoore/Pierre_sc_zebrafish/seurat_mouse_annot_sham.rds_cellchat_20250520_100324/"
cellchat <- readRDS(file=paste0(output,"cellchat_obj.rds"))
```

```{r}
# Manifold and classification learning analysis of signaling networks
#  quantify the similarity between all significant signaling pathways and then group them based on their cellular communication network similarity.
# activate correct python env
reticulate::use_python("/w5home/bmoore/.virtualenvs/cellchat/bin/python")
#Identify signaling groups based on their functional similarity
cellchat <- computeNetSimilarity(cellchat, type = "functional")
#umap manifoldlearning
cellchat <- netEmbedding(cellchat, type = "functional")
# classification of signaling network
cellchat <- netClustering(cellchat, type = "functional")
# Visualization in 2D-space
pf <- netVisual_embedding(cellchat, type = "functional", label.size = 3.5)
pdf(file=paste0(output, name, "_pathway_functionality_2Dplot.pdf"))
print(pf)
dev.off()
pz <- netVisual_embeddingZoomIn(cellchat, type = "functional", nCol = 2)
pdf(file=paste0(output, name, "_pathway_functionality_2Dplot_zoom.pdf"))
print(pz)
dev.off()
```

```{r}
# Identify signaling groups based on structure similarity
cellchat <- computeNetSimilarity(cellchat, type = "structural")
cellchat <- netEmbedding(cellchat, type = "structural")
cellchat <- netClustering(cellchat, type = "structural")
# Visualization in 2D-space
ps <- netVisual_embedding(cellchat, type = "structural", label.size = 3.5)
pdf(file=paste0(output, name, "_pathway_structural_2Dplot.pdf"))
print(ps)
dev.off()
# zoom in
pz <- netVisual_embeddingZoomIn(cellchat, type = "structural", nCol = 2)
pdf(file=paste0(output, name, "_pathway_structural_2Dplot_zoomin.pdf"))
print(pz)
dev.off()
```

```{r save}
print(paste0("saving object: ", name))
saveRDS(cellchat, file=paste0(output,"cellchat_obj.rds"))
writeLines(capture.output(sessionInfo()), paste0(output,"sessionInfo.txt"))
```

```{r extra}
# pull matrices out of cellchat object
prob_matrix <- cellchat@net$prob
weight_matrix <- cellchat@net$weight
print(head(prob_matrix))
print(head(weight_matrix))
df.net <- subsetCommunication(cellchat)
```
```{r}
seurat_obj <- readRDS(file="/w5home/bmoore/Pierre_sc_zebrafish/seurat_mouse_annot_sham.rds")
print(seurat_obj)
colnames(seurat_obj@meta.data)
table(seurat_obj$orig.ident)
table(seurat_obj$sample)
seurat_obj2 <- readRDS(file="/w5home/bmoore/Pierre_sc_zebrafish/seurat_mouse_annot_1wk.rds")
colnames(seurat_obj2@meta.data)
table(seurat_obj2$orig.ident)
```
```{r subset}
seurat_obj1_43 <- subset(x = seurat_obj, subset = orig.ident == "43")
seurat_obj1_43
colnames(seurat_obj1_43@meta.data)
table(seurat_obj1_43$CellType)

seurat_obj1_44 <- subset(x = seurat_obj, subset = orig.ident == "44")
seurat_obj1_44
colnames(seurat_obj1_44@meta.data)
table(seurat_obj1_44$CellType)
```
```{r}
setwd("/w5home/bmoore/Pierre_sc_zebrafish/")
seurat_obj <- readRDS(file="seurat_mouse_annot_4wkNR.rds")
filename="seurat_mouse_annot_4wkNR"
```
```{r subset_save}
reps <- unique(seurat_obj$orig.ident)
for(i in 1:length(reps)){
        rep = as.character(reps[i])
        print(rep)
        seurat_sub <- subset(x = seurat_obj, subset = orig.ident == rep)
        print(seurat_sub)
        print(table(seurat_sub$CellType))
        saveRDS(seurat_sub, file = paste0(filename, "_", rep, ".rds"))
}
```