---
title: "clustifyr"
author: "Beth Moore"
date: "2023-09-22"
output: html_document
---

# clustifyr analysis for automatic cell type annotation with marker list or reference
# To run clustifyr, you need clustered seurat object

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#### installations ####
# see scRNAseq_library/src/clustifyr_setup.sh or
# use create conda environment with environment_scRNAseq-clustifyr.yml
# 

### load libraries ###
library(reticulate)
use_condaenv("/w5home/bmoore/miniconda3/envs/scRNAseq_best")
library(clustifyr)
library(ggplot2)
library(cowplot)
library(Seurat)
library(ComplexHeatmap)
library(rmarkdown)
library(purrr)
library(jsonlite)
library(dplyr)
### set variables ###
GIT_DIR <- "/w5home/bmoore/scRNAseq_downstream/"
config <- fromJSON(file.path(GIT_DIR, "config.json"))
WD <- config$clustifyr$DATA_DIR
REF.SEURAT <-  config$clustifyr$REF.SEURAT # if NA, only marker list is used
QUERY.SEURAT <- config$clustifyr$QUERY.SEURAT
cluster_name <- config$clustifyr$cluster_name
### set working directory and output ###
setwd(WD)
timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
output <- paste0("output_clustifyr_", timestamp)
dir.create(output, showWarnings = FALSE)
output <- paste0(output, "/")
## copy config to output
file.copy(paste0(GIT_DIR,"config.json"), file.path(output, "config.json"))
## source config and functions
config <- fromJSON(file.path(output, "config.json"))
source(paste0(GIT_DIR,"src/sc_pipeline_functions.R"))
```
# load data set and marker list
```{r load_data}
# load data set
seurat.obj <- readRDS(file = QUERY.SEURAT)
# load reference
if(REF.SEURAT!="NA"){
ref.seurat<- readRDS(file = REF.SEURAT)
} else {
  print("No reference, using marker list only")
}
```
# rename identities if necessary
```{r rename_idents}
# check metadata
colnames(seurat.obj@meta.data)
# stash idents
seurat.obj[["cell.cycle"]] <- Idents(object = seurat.obj)
# make clusters idents
Idents(object = seurat.obj) <- cluster_name
table(Idents(object = seurat.obj))
# convert to character
seurat.obj@meta.data[cluster_name] <- mutate_if(seurat.obj@meta.data[cluster_name], is.factor, as.character)
unique(seurat.obj[[cluster_name]])
# remove NAs
if(cluster_name=="seurat_clusters"){
  seurat.obj<- subset(seurat.obj, subset = seurat_clusters != "NA")
} else if (cluster_name=="seurat_clusters2"){
  seurat.obj<- subset(seurat.obj, subset = seurat_clusters2 != "NA")
} else if (cluster_name=="cca_clusters"){
  seurat.obj<- subset(seurat.obj, subset = cca_clusters != "NA")
} else {
  print(paste0("Not able to remove NAs from clusters: ",cluster_name,". 
  Clustifyr may throw an error if NAs are present in clusters."))
}

```

# run clustifyr from marker list
```{r clustifyr}
# convert to single cell experiment
SCE <- as.SingleCellExperiment(seurat.obj)
# run clustifyr
seurat.obj<- annotate_with_clustifyR(seurat.obj, SCE, output, "clustifyr")
```

# run clustifyr with references
```{r clustifyr_ref}
if(REF.SEURAT!="NA"){
  
  #visualize and subset
  ref.seurat.sub <- visualize_and_subset_ref(ref.seurat, output, "clustifyr")
  # annotate with clustifyr
  clustifyr.obj <- annotate_with_clustifyR_ref(ref.seurat.sub, seurat.obj, SCE, output, "clustifyr")

} else {
  print("no references, quitting")
  q()
}
```
