
# load packages
```{r load_packages}
library(Seurat)
library(SeuratData)
library(patchwork)
library(scran)
library(BiocParallel)
library(cowplot)
library(reticulate)
library(purrr)
library(jsonlite)
library(rmarkdown)
library(ggplot2)
library(scater)
library(SingleCellExperiment)
library(tidyverse)
library(DESeq2)
library(dplyr)
```
# set dir and filenames
```{r dir_file}
GIT_DIR <- "/w5home/bmoore/scRNAseq_downstream/src/" #getwd()
DATA_DIR <- "/w5home/bmoore/Pierre_sc_zebrafish/"
setwd(DATA_DIR)
#### make output dir  and read in data ####
timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
output <- paste0(DATA_DIR, "DEseq2_",timestamp)
print(output)
dir.create(output, mode = "0777", showWarnings = FALSE)
```
# read in 2 seurat objects as a list (one control, one condition)
```{r read_in}
# load data
setwd(DATA_DIR)
# Create an empty list to store the imported objects
imported_objects <- list()
print("loading data")
# Loop through the filenames
for (i in seq_along(filename_list)) {
  # Extract the base filename without extension
  base_name <- tools::file_path_sans_ext(basename(filename_list[i]))
  # Import the file
  imported_object <- readRDS(filename_list[i])
  # Assign the imported object to the list with the base filename as the name
  imported_objects[[base_name]] <- imported_object
}
# reset dir
setwd(GIT_DIR)
# Convert the list to a vector
seurat_vector <- unlist(imported_objects)
vector<- c()
for(i in 2:length(seurat_vector)){
    vector <- c(vector, seurat_vector[[i]])
}
# First, find the common features across all objects
common_features <- Reduce(intersect, lapply(seurat_vector, rownames))
# Subset each object to only these common features
seurat_vector <- lapply(seurat_vector, function(obj) {
  obj[common_features, ]
})
seurat_vector <- lapply(seurat_vector, function(obj) {
  obj[["RNA"]] <- JoinLayers(obj[["RNA"]])
  return(obj)})
# This will be used to give unique identifiers to cells from each object
object_names <- names(imported_objects)
if (is.null(object_names)) {
  object_names <- paste0("Object", seq_along(imported_objects))
}

# Now, we'll merge the objects
print("merging seurat objects")
merged_seurat <- merge(x = seurat_vector[[1]], y = seurat_vector[[2]], 
                        add.cell.ids = object_names, 
                        project = "2wk_comparison", merge.data = TRUE) #config$seurat_integration$project_name
print(merged_seurat)
merged_seurat[["RNA"]] <- JoinLayers(merged_seurat)
```
# read in already merged
```{r readin_merged}
merged_seurat <- readRDS(file = paste0(DATA_DIR, "SCI6WK_PARSE_PG_SB_030123.rds"))
print(merged_seurat)
colnames(merged_seurat@meta.data)
```
# get metadata for cell types
```{r metadata}
# clusterids <- read.csv(paste0(DATA_DIR, "celltype_annot_df.csv"), header = TRUE)
# print(clusterids)
# new_df_ordered <- clusterids[order(as.numeric(clusterids$Cluster)), ]
# new_cluster_ids <- new_df_ordered$Celltype
# print(new_cluster_ids)
# # make sure that idents are the clusters you want annotated
# merged_seurat <- SetIdent(merged_seurat, value = "seurat_clusters")
# # Rename the clusters based on the new IDs
# names(new_cluster_ids) <- levels(merged_seurat)
# merged_seurat <- RenameIdents(merged_seurat, new_cluster_ids)
# # put in CellType metadata
# merged_seurat$CellType <- Idents(merged_seurat)

# # Generate and plot the UMAP plot
# pdf(paste0(DATA_DIR, "labeled-clusters.pdf"), bg = "white")
# print(DimPlot(merged_seurat, reduction = "umap", label = TRUE, 
#         pt.size = 0.5, group.by = "CellType"))
# dev.off()

# set idents to cluster value
merged_seurat <- SetIdent(merged_seurat, value = "seurat_clusters")
# rename by hand
merged_seurat <-RenameIdents(merged_seurat, `0` = "Radial_Glial_Cells")
merged_seurat <-RenameIdents(merged_seurat, `1` = "Schwann_Cells")
merged_seurat <-RenameIdents(merged_seurat, `2` = "Gabaergic_Neurons")
merged_seurat <-RenameIdents(merged_seurat, `3` = "Microglial_Cells")
merged_seurat <-RenameIdents(merged_seurat, `4` = "Immature_Neurons")
merged_seurat <-RenameIdents(merged_seurat, `5` = "T_Cells_and_Neutrophils")
merged_seurat <-RenameIdents(merged_seurat, `6` = "Glutamatergic_Neurons")
merged_seurat <-RenameIdents(merged_seurat, `7` = "Fibroblasts")
merged_seurat <-RenameIdents(merged_seurat, `8` = "Oligodendrocytes_maybe")
merged_seurat <-RenameIdents(merged_seurat, `9` = "Oligodendrocytes_progenitor_cells")
merged_seurat <-RenameIdents(merged_seurat, `10` = "Unknown1")
merged_seurat <-RenameIdents(merged_seurat, `11` = "Macrophages")
merged_seurat <-RenameIdents(merged_seurat, `12` = "Glycinergic_Neurons")
merged_seurat <-RenameIdents(merged_seurat, `13` = "Motor_Neurons")
merged_seurat <-RenameIdents(merged_seurat, `14` = "Unknown2")
merged_seurat <-RenameIdents(merged_seurat, `15` = "Endothelial_Cells")
merged_seurat <-RenameIdents(merged_seurat, `16` = "Keratinocytes")
merged_seurat <-RenameIdents(merged_seurat, `17` = "Unknown3")

# put in CellType metadata
merged_seurat$CellType <- Idents(merged_seurat)
```
```{r plot}
# Generate and plot the UMAP plot
pdf(paste0(output, "/seurat-clusters_zfish_umap.pdf"), bg = "white", width=10, height=6)
print(DimPlot(merged_seurat, reduction = "umap", label = TRUE,
        pt.size = 0.5, group.by = "seurat_clusters"))
dev.off()

pdf(paste0(output, "/CellType_zfish_umap.pdf"), bg = "white", width=10, height=6)
print(DimPlot(merged_seurat, reduction = "umap", label = TRUE,
        pt.size = 0.5, group.by = "CellType"))
dev.off()
```
```{r}
# save
library(qs2)
print("saving object")
# sham
qs_save(merged_seurat, "seurat_zfish_annot_all.qs2")
# convert to rds
qs_to_rds(input_file = "seurat_zfish_annot_all.qs2", output_file = "seurat_zfish_annot_all.rds")
```
```{r readin}
# read in already processed
merged_seurat <- readRDS(file = "/w5home/bmoore/Pierre_sc_zebrafish/seurat_zfish_annot_all.rds")
print(merged_seurat)
colnames(merged_seurat@meta.data)
```
# Pseudobulk analysis
```{r pseudobulk}
# pseudobulk cells by stimulation condition AND cell type
bulk_seurat <- AggregateExpression(merged_seurat, assays = "RNA", 
                                group.by = c("Type", "orig.ident","CellType"), 
                                return.seurat = TRUE) #, layer = "counts"
Cells(bulk_seurat)
# make new celltype column
bulk_seurat$celltype.comp <- paste(bulk_seurat$CellType, bulk_seurat$Type, sep = "_")
Idents(bulk_seurat) <- "celltype.comp"
```
# De analysis across conditions
```{r de}
bulk.F.de <- FindMarkers(object = bulk_seurat, 
                         ident.1 = "Fibroblasts_g4Wk-R", 
                         ident.2 = "Fibroblasts_g4Wk-NR",
                         logfc.threshold = 0.5,
                         test.use = "DESeq2") # DESeq2 requires counts, DESeq2 or MAST
head(bulk.F.de, n = 15)
dim(bulk.F.de)
#bulk.F.de <- subset(bulk.F.de, p_val_adj < 0.05)
```
# write table
```{r}
# order
bulk.F.de <- bulk.F.de[with(bulk.F.de, order(p_val_adj, -avg_log2FC)), ]

write.table(bulk.F.de, file = paste0(output, "/", "Fibroblasts_4Wk", 
                "_R-NR_DE_genes_lfc_0.5_DESeq2.txt"), sep="\t")
top.10.genes <- rownames(bulk.F.de)[1:15]
print(top.10.genes)
```
# violin plot
```{r vplot}
# create a new column to annotate sample-condition-celltype in the single-cell dataset
merged_seurat$celltype.comp <- paste(merged_seurat$CellType, merged_seurat$Type, sep = "_")
Idents(merged_seurat) <- "celltype.comp"
# violin plot
pdf(paste0(output,"/","violinplot_fibroblast_4wk_DE_mast.pdf"), bg = "white")
print(VlnPlot(merged_seurat, features = top.10.genes, 
      idents = c("Fibroblasts_4Wk-NR", "Fibroblasts_4Wk-R"),
      group.by = "Type"))
dev.off()
```
# all collagen/ connective genes
```{r vplot2}
col.genes1 <- c("TIGIT","CD226","TGFB1A","TGFB2","TGFB3","TGFB5","TGFBR1A","TGFBR2B","TGFBR3",
              "COL1A2","COL1A1A","COL1A1B")
col.genes2 <- c("COL4A1","COL4A2","COL4A4","COL4A5","COL4A6",
              "COL5A1","COL5A2A","COL5A2B","COL5A3A","PDGFAB","PDGFBB")
pdf(paste0(output,"/","violinplot_fibroblast_4wk_col.genes1.pdf"), bg = "white")
print(VlnPlot(merged_seurat, features = col.genes1, 
      idents = c("Fibroblasts_4Wk-NR", "Fibroblasts_4Wk-R"),
      group.by = "Type"))
dev.off()
pdf(paste0(output,"/","violinplot_fibroblast_4wk_col.genes2.pdf"), bg = "white")
print(VlnPlot(merged_seurat, features = col.genes2, 
      idents = c("Fibroblasts_4Wk-NR", "Fibroblasts_4Wk-R"),
      group.by = "Type"))
dev.off()
```
```{r bubbleplot}
pdf(paste0(output,"/","bubbleplot_fibroblast_4wk_col.genes1.pdf"), bg = "white")
print(DotPlot(merged_seurat, features = col.genes1,
        idents = c("Fibroblasts_4Wk-NR", "Fibroblasts_4Wk-R"),
        group.by = "Type") + RotatedAxis())
dev.off()

pdf(paste0(output,"/","bubbleplot_fibroblast_4wk_col.genes2.pdf"), bg = "white")
print(DotPlot(merged_seurat, features = col.genes2,
        idents = c("Fibroblasts_4Wk-NR", "Fibroblasts_4Wk-R"),
        group.by = "Type") + RotatedAxis())
dev.off()
```
# axon guidance genes
```{r axon_genes}
axon_df <- read.csv("/w5home/bmoore/Pierre_sc_zebrafish/zfin_search_results_axonguidegenes.csv", header= TRUE)
axon_df = as.data.frame(sapply(axon_df, toupper))
print(axon_df)
axon.genes <- axon_df$name
print(axon.genes)
```
# plot axon genes
```{r vplot}
x=1
for(i in seq(from=1, to=395, by=12)){
  print(i)
  j = i+11
  if(j > 395){
    j = 395
  }
  print(j)
  pdf(paste0(output,"/","violinplot_fibroblast_4wk_axon.genes",x,".pdf"), bg = "white")
  print(VlnPlot(merged_seurat, features = axon.genes[i:j], 
      idents = c("Fibroblasts_4Wk-NR", "Fibroblasts_4Wk-R"),
      group.by = "Type"))
  dev.off()
  x=x+1
}
```
# add in if axon gene
```{r}
bulk.F.de <- bulk.F.de %>%
  mutate(axon_gene = ifelse(row.names(bulk.F.de) %in% axon.genes, 1, 0))
```

# Loop
```{r loop}
merged_seurat$celltype.comp <- paste(merged_seurat$CellType, merged_seurat$Type, sep = "_")
comparisons <- c("2Wk","4Wk","6Wk") #
celltypes <- as.vector(unique(merged_seurat$CellType))
for(i in 1:length(celltypes)){
  celltype <- celltypes[i]
  if(grepl("_", celltype,fixed = TRUE)==TRUE){
    celltype1 <- gsub("_", "-", celltype)
  } else {
    celltype1 <- celltype
  }
  print(celltype1)
  for(j in 1:length(comparisons)){
    week <- comparisons[j]
    print(week)
    # do DE
    # because Recovered is the first group, positive logFC values are more highly expressed in recovered
    tryCatch({
    bulk.de <- FindMarkers(object = bulk_seurat, 
                          ident.1 = paste0(celltype1,"_g",week,"-R"), 
                          ident.2 = paste0(celltype1,"_g",week,"-NR"),
                          test.use = "DESeq2", logfc.threshold = 0.5) # DESeq2 requires counts
    # subset for significance
    bulk.de <- as.data.frame(bulk.de)
    bulk.de <- subset(bulk.de, p_val_adj < 0.05)
    bulk.de <- subset(bulk.de, avg_log2FC >= 0.5 | avg_log2FC <= -0.5)
    print(head(bulk.de))
    # order
    bulk.de <- bulk.de[with(bulk.de, order(p_val_adj, -avg_log2FC)), ]
    # add axon gene
    bulk.de <- bulk.de %>%
      mutate(axon_gene = ifelse(row.names(bulk.de) %in% axon.genes, 1, 0))
    # write out
    write.table(bulk.de, file = paste0(output, "/", celltype1, week, 
                "_R-NR_DEseq2_genes_lfc0.5.txt"), sep="\t")
    },
    error = function(cond) {
      message(conditionMessage(cond))
      bulk.de <- data.frame()
    }
    )
    # check if dataframe is not empty
    if (dim(bulk.de)[1] != 0) {
      # get top 10 genes
      if (dim(bulk.de)[1] < 10){
        n <- dim(bulk.de)[1]
        top.10.genes <- rownames(bulk.de)[1:n]
      } else {
        top.10.genes <- rownames(bulk.de)[1:10]
      }
      top.10.genes <- unique(top.10.genes)
      top.10.genes <- top.10.genes[!is.na(top.10.genes)]
      # make violin plot with top10
      pdf(paste0(output, "/violinplot_",celltype, week,"_DEseq2_lfc0.5.pdf"), bg = "white")
      print(VlnPlot(merged_seurat, features = top.10.genes,
          idents = c(paste0(celltype,"_",week,"-NR"), paste0(celltype,"_",week,"-R")), 
          group.by = "Type"))
      dev.off()
      # with bulk
      pdf(paste0(output, "/violinplot_",celltype1, week,"_DEseq2_lfc0.5_bulk.pdf"), bg = "white")
      print(VlnPlot(bulk_seurat, features = top.10.genes,
          idents = c(paste0(celltype1,"_g",week,"-NR"), paste0(celltype1,"_g",week,"-R")), 
          group.by = "Type"))
      dev.off()
    } else {
      print(paste0(celltype,"_",week," has no DE genes between R and NR"))
    }
  }

}
```
# for sham vs 1 week comparisons
```{r}
celltypes <- as.vector(unique(merged_seurat$CellType))
for(i in 1:length(celltypes)){
  celltype <- celltypes[i]
  if(grepl("_", celltype,fixed = TRUE)==TRUE){
    celltype1 <- gsub("_", "-", celltype)
  } else {
    celltype1 <- celltype
  }
  print(celltype1)
  tryCatch({
    bulk.de <- FindMarkers(object = bulk_seurat, 
                          ident.1 = paste0(celltype1,"_g1Wk"), 
                          ident.2 = paste0(celltype1,"_Sham"),
                          test.use = "DESeq2", logfc.threshold = 0.5) # DESeq2 requires counts
    # subset for significance
    bulk.de <- subset(bulk.de, p_val_adj < 0.05)
    bulk.de <- subset(bulk.de, avg_log2FC >= 0.5 | avg_log2FC <= -0.5)
    bulk.de <- as.data.frame(bulk.de)
    # order
    bulk.de <- bulk.de[with(bulk.de, order(p_val_adj, -avg_log2FC)), ]
    # add axon gene
    bulk.de <- bulk.de %>%
      mutate(axon_gene = ifelse(row.names(bulk.de) %in% axon.genes, 1, 0))
    # write out
    write.table(bulk.de, file = paste0(output, "/", celltype1, week, 
                "_R-NR_DE_genes_lfc0.5.txt"), sep="\t")
    },
    error = function(cond) {
      message(conditionMessage(cond))
      bulk.de <- data.frame()
    }
  )
  # check if dataframe is not empty
  if (dim(bulk.de)[1] != 0) {
    # get top 10 genes
    if (dim(bulk.de)[1] < 10){
        n <- dim(bulk.de)[1]
        top.10.genes <- rownames(bulk.de)[1:n]
    } else {
        top.10.genes <- rownames(bulk.de)[1:10]
    }
    top.10.genes <- unique(top.10.genes)
    top.10.genes <- top.10.genes[!is.na(top.10.genes)]
    # make violin plot with top10
    pdf(paste0(output, "/", "violinplot_",celltype1, "_1Wk-Sham_DE__lfc0.5.pdf"), bg = "white")
    print(VlnPlot(merged_seurat, features = top.10.genes, 
        idents = c(paste0(celltype,"_Sham"), paste0(celltype,"_1Wk")), 
        group.by = "Type"))
    dev.off()
    # with bulk
      pdf(paste0(output, "/violinplot_",celltype1, "_1Wk-Sham_DEseq2_lfc0.5_bulk.pdf"), bg = "white")
      print(VlnPlot(bulk_seurat, features = top.10.genes,
          idents = c(paste0(celltype1,"_g",week,"-NR"), paste0(celltype1,"_g",week,"-R")), 
          group.by = "Type"))
      dev.off()
  } else {
      print(paste0(celltype," has no DE genes between Sham and 1Wk"))
  }
}
```
```{r vlnplot_bulk}
col.genes1 <- c("TIGIT","CD226","TGFB1A","TGFB2","TGFB3","TGFB5","TGFBR1A","TGFBR2B","TGFBR3",
              "COL1A2","COL1A1A","COL1A1B")
col.genes2 <- c("COL4A1","COL4A2","COL4A4","COL4A5","COL4A6",
              "COL5A1","COL5A2A","COL5A2B","COL5A3A","PDGFAB","PDGFBB")
pdf(paste0(output,"/","violinplot_fibroblast_4wk_col.genes1_bulk.pdf"), bg = "white")
    print(VlnPlot(bulk_seurat, features = col.genes1,
          idents = c("Fibroblasts_g4Wk-NR", "Fibroblasts_g4Wk-R"), 
          group.by = "Type"))
dev.off()
pdf(paste0(output,"/","violinplot_fibroblast_4wk_col.genes2_bulk.pdf"), bg = "white")
    print(VlnPlot(bulk_seurat, features = col.genes2,
          idents = c("Fibroblasts_g4Wk-NR", "Fibroblasts_g4Wk-R"), 
          group.by = "Type"))
dev.off()
```
```{r vlnplottest}
library(Seurat)
library(SeuratData)
sessionInfo()
InstallData("pbmc3k")
data("pbmc3k")
pbmc3k <- UpdateSeuratObject(pbmc3k)
VlnPlot(pbmc3k, features = "nFeature_RNA")
```
```{r outputexprs}
df <- as.data.frame(merged_seurat[["RNA"]]$data)
write.csv(df, file = paste0(output,"/seurat_zfish_annot_all_norma_expr_data.csv"))
```