---
title: "reannotate gamm clusters"
output: html_document
---

# ENVIRONMENT SETUP

```{r env, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(Seurat)
library(patchwork)
library(BiocParallel)
library(cowplot)
library(reticulate)
library(purrr)
library(jsonlite)
library(rmarkdown)
library(ggplot2)
library(tidyverse)
library(tibble)
library(scran)

BETHS_GAMM_DATA_DIR <- "/w5home/bmoore/scRNAseq/GAMM/"
GIT_DIR <- "/w5home/bmoore/Gamm_scRNAseq/"
use_condaenv("scRNAseq_best")
WD <- paste0(BETHS_GAMM_DATA_DIR) #, "GAMM_S1/"
setwd(WD)
timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
output <- paste0("GAMM_S1/output_reannotate_", timestamp)
dir.create(output, showWarnings = TRUE)
file.copy(paste0(GIT_DIR,"config.json"), file.path(output, "config.json"))
config <- fromJSON(file.path(output, "config.json"))
output <- paste0(output, "/")
source(paste0(GIT_DIR,"src/sc_pipeline_functions.R"))
```
# Load Data
```{r load_data}
gamms2<- readRDS(file = "GAMM_S1/output_20230921_142919/clustered_seurat_obj.rds")
```
# check metadata
```{r metadata}
colnames(gamms2@meta.data)
unique(gamms2@active.ident)
unique(gamms2@meta.data$seurat_clusters)
colnames(gamms2@assays$RNA@data)[1:10]
```

# score an plot markers using new markers
```{r score_markers}
annot_df <- score_and_plot_markers(gamms2)
```

```{r}

annot_df.ordered <- annot_df[order(as.numeric(annot_df$Cluster)), ]
new.cluster.ids <- annot_df.ordered$Cell.type
print(new.cluster.ids)
```
# annotate
```{r annotate}
gamms2.annot <- annotate_clusters_and_save(gamms2, new.cluster.ids)
```
# save annotation as dataframe
```{r save_annot}
gamm.metadata<- as.data.frame(gamms2.annot@meta.data)
write.table(gamm.metadata, file = paste0(output,"gammS2_manual_annot_metadata_c0.5_KR.txt"), sep="\t", 
            quote=F, row.names = T)
```

# read back in metadata
```{r get_meta}
# add in metadata from previous analysis
metadata.gamm <- read.csv("/w5home/bmoore/scRNAseq/GAMM/gamm_metadata/gammS2_manual_annot_metadata_c0.5.txt", 
            row.names = 1, header = TRUE, sep = "\t")
# check metadata with query data
colnames(gamms2@assays$RNA@data)[1:10]
rownames(metadata.gamm)[1:10]

# add metadata to query data
gamms2 <- AddMetaData(gamms2, metadata.gamm)

# check again
colnames(gamms2@meta.data)
table(gamms2@meta.data$CellType_manual)
```
# visualize
```{r visualize_clusters}
pdf("gamms2_umap_new_manual_IDs.pdf", width = 8, height = 6)
  umap_clusters <- DimPlot(gamms2, reduction = "umap", group.by = "CellType_manual", 
                          label = TRUE, pt.size = .1)
  print(umap_clusters)
  dev.off()
```
# save object
```{r save}
saveRDS(gamms2, file = "GAMM_S2_clabeled-clusters_0.5.rds")
```
