---
title: "scType annotation"
author: "Beth Moore"
date: "2024-09-16"
output: html_document
---
```{r load_libraries}
# load libraries
library(reticulate)
use_condaenv("/w5home/bmoore/miniconda3/envs/scRNAseq_best", required=TRUE)
lapply(c("dplyr","Seurat","HGNChelper","openxlsx"), library, character.only = T)
library(jsonlite)
# set variables
GIT_DIR <- "/w5home/bmoore/scRNAseq_downstream/"
config <- fromJSON(file.path(GIT_DIR, "config.json"))
WD <- config$sctype$WD
SEURAT.FILE <- config$sctype$SEURAT_OBJ
DB <- config$sctype$db
TISSUE <- config$sctype$tissue
setwd(WD)
file.copy(paste0(GIT_DIR,"config.json"), file.path(WD, "config_sctype.json"))
```
```{r install_sctype}
# load gene set preparation function
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R")
# load cell type annotation function
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")
```
```{r DB_file}
# DB file
if (DB=="default"){
  db_ <- "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_full.xlsx"
} else {
  db_ <- DB
}
tissue <- TISSUE 
# e.g. Immune system,Pancreas,Liver,Eye,Kidney,Brain,Lung,Adrenal,Heart,Intestine,
# Muscle,Placenta,Spleen,Stomach,Thymus

# prepare gene sets
gs_list <- gene_sets_prepare(db_, tissue)
```
# load seurat
```{r load_seurat}
seurat.obj <- readRDS(file=SEURAT.FILE)
```
# assign cell types
```{r}
# get assay data
xl <- Assays(seurat.obj)

# extract scaled scRNA-seq matrix
as.matrix(seurat.obj[[xl]]$scale.data) 

# run ScType
es.max <- sctype_score(scRNAseqData = scRNAseqData_scaled, scaled = TRUE, 
                      gs = gs_list$gs_positive, gs2 = gs_list$gs_negative)

# NOTE: scRNAseqData parameter should correspond to your input scRNA-seq matrix. For raw (unscaled) count matrix set scaled = FALSE
# When using Seurat, we use "RNA" slot with 'scale.data' by default. Please change "RNA" to "SCT" for sctransform-normalized data,
# or to "integrated" for joint dataset analysis. To apply sctype with unscaled data, use e.g. pbmc[["RNA"]]$counts or pbmc[["RNA"]]@counts, with scaled set to FALSE.

# merge by cluster
cL_resutls <- do.call("rbind", lapply(unique(seurat.obj@meta.data$seurat_clusters), 
            function(cl){
              es.max.cl = sort(rowSums(es.max[ ,rownames(seurat.obj@meta.data[seurat.obj@meta.data$seurat_clusters==cl, ])]), decreasing = !0)
              head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(seurat.obj@meta.data$seurat_clusters==cl)), 10)
}))
sctype_scores <- cL_resutls %>% group_by(cluster) %>% top_n(n = 1, wt = scores)  

# set low-confident (low ScType score) clusters to "unknown"
sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) < sctype_scores$ncells/4] <- "Unknown"
print(sctype_scores[,1:3])
```
```{r plot}
seurat.obj@meta.data$sctype_classification = ""
for(j in unique(sctype_scores$cluster)){
  cl_type = sctype_scores[sctype_scores$cluster==j,]; 
  seurat.obj@meta.data$sctype_classification[seurat.obj@meta.data$seurat_clusters == j]= as.character(cl_type$type[1])
}
pdf(paste0("sctype_umap.pdf"), bg = "white")
print(DimPlot(seurat.obj, reduction = "umap", label = TRUE,
      repel = TRUE, group.by = 'sctype_classification'))
dev.off()
```
```{r wrapper}
# source("https://raw.githubusercontent.com/kris-nader/sc-type/master/R/sctype_wrapper.R"); 
# pbmc <- run_sctype(seurat.obj,known_tissue_type="Immune system",custom_marker_file=
#                 "https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/ScTypeDB_full.xlsx",
#                 name="sctype_classification",plot=TRUE)
```
# bubble plot
```{r bubble}
# load libraries
lapply(c("ggraph","igraph","tidyverse", "data.tree"), library, character.only = T)

# prepare edges
cL_resutls <- cL_resutls[order(cL_resutls$cluster),]; edges = cL_resutls; 
              edges$type = paste0(edges$type,"_",edges$cluster); 
              edges$cluster = paste0("cluster ", edges$cluster); 
              edges = edges[,c("cluster", "type")]; colnames(edges) = c("from", "to"); rownames(edges) <- NULL

# prepare nodes
nodes_lvl1 <- sctype_scores[,c("cluster", "ncells")]; 
              nodes_lvl1$cluster = paste0("cluster ", nodes_lvl1$cluster); 
              nodes_lvl1$Colour = "#f1f1ef"; nodes_lvl1$ord = 1; 
              nodes_lvl1$realname = nodes_lvl1$cluster; 
              nodes_lvl1 = as.data.frame(nodes_lvl1); nodes_lvl2 = c(); 
ccolss <- c("#5f75ae","#92bbb8","#64a841","#e5486e","#de8e06","#eccf5a",
            "#b5aa0f","#e4b680","#7ba39d","#b15928","#ffff99", "#6a3d9a",
            "#cab2d6","#ff7f00","#fdbf6f","#e31a1c","#fb9a99","#33a02c",
            "#b2df8a","#1f78b4","#a6cee3")
for (i in 1:length(unique(cL_resutls$cluster))){
  dt_tmp = cL_resutls[cL_resutls$cluster == unique(cL_resutls$cluster)[i], ]; 
  nodes_lvl2 = rbind(nodes_lvl2, data.frame(cluster = paste0(dt_tmp$type,"_",
  dt_tmp$cluster), ncells = dt_tmp$scores, Colour = ccolss[i], ord = 2, realname = dt_tmp$type))
}
nodes <- rbind(nodes_lvl1, nodes_lvl2); nodes$ncells[nodes$ncells<1] = 1;
files_db <- openxlsx::read.xlsx(db_)[,c("cellName","shortName")]; 
files_db = unique(files_db); 
nodes = merge(nodes, files_db, all.x = T, all.y = F, by.x = "realname", by.y = "cellName", sort = F)
nodes$shortName[is.na(nodes$shortName)] = nodes$realname[is.na(nodes$shortName)]; 
nodes = nodes[,c("cluster", "ncells", "Colour", "ord", "shortName", "realname")]

mygraph <- graph_from_data_frame(edges, vertices=nodes)
```
# Make the graph
```{r bubbleplot}
gggr <- ggraph(mygraph, layout = 'circlepack', weight=I(ncells)) + 
  geom_node_circle(aes(filter=ord==1,fill=I("#F5F5F5"), colour=I("#D3D3D3")), alpha=0.9) +
  geom_node_circle(aes(filter=ord==2,fill=I(Colour), colour=I("#D3D3D3")), alpha=0.9) +
  theme_void() + geom_node_text(aes(filter=ord==2, label=shortName, colour=I("#000000"), 
  fill="white", repel = !1, parse = T, size = I(log(ncells,25)*1.5)))+ NoLegend() 
  #geom_node_label(aes(filter=ord==1,  label=shortName, colour=I("#000000"), size = I(2), 
  #fill="white", parse = T), repel = !0, segment.linetype="dotted")

pdf(paste0("sctype_bubbleplot.pdf"), bg = "white", width=8, height=4)  
print(DimPlot(seurat.obj, reduction = "umap", label = TRUE, repel = TRUE, 
      group.by = 'sctype_classification', cols = ccolss)+ gggr)
dev.off()
```
```{r rename_save}
# rename
#seurat.obj$sctype_classification_ybthymus <- seurat.obj$sctype_classification
# delete old
#seurat.obj$sctype_classification <- NULL
saveRDS(seurat.obj, file="seurat_obj_labeled_sctype.rds")
```