---
title: "seurat_integration_for_cross_species"
author: "Beth Moore"
date: "2023-07-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(patchwork)
library(purrr)
library(jsonlite)
library(rmarkdown)
library(reticulate)
library(multtest)
library(metap)
library(harmony)
library(SeuratWrappers)
library(Azimuth)
library(ggplot2)
library(scran)
library(clustifyr)
use_condaenv("/w5home/bmoore/miniconda3/envs/scRNAseq_best")

# set variables
GIT_DIR <- "/w5home/bmoore/scRNAseq_downstream/"
config <- fromJSON(file.path(GIT_DIR, "config.json"))
WD <- config$seurat_integration$DATA_DIR
filename_list <- config$seurat_integration$filename_list
# set up environment and output
setwd(WD)
timestamp <- format(Sys.time(), "%Y%m%d_%H%M%S")
output <- paste0("output_seuratintegrate_", timestamp)
dir.create(output, showWarnings = FALSE)
file.copy(paste0(GIT_DIR,"config.json"), file.path(output, "config.json"))
output <- paste0(output, "/")
config <- fromJSON(file.path(output, "config.json"))
source(paste0(GIT_DIR,"src/sc_pipeline_functions.R"))
```

# load data
```{r load_data}
# Create an empty list to store the imported objects
imported_objects <- list()

# Loop through the filenames
for (i in seq_along(filename_list)) {
  # Extract the base filename without extension
  base_name <- tools::file_path_sans_ext(basename(filename_list[i]))
  
  # Import the file
  imported_object <- readRDS(filename_list[i])
  
  # Assign the imported object to the list with the base filename as the name
  imported_objects[[base_name]] <- imported_object
}
```
# merge into one object
```{r merge}
# merge
# Convert the list to a vector
seurat_vector <- unlist(imported_objects)
vector<- seurat_vector[[2]]
for(i in 3:length(seurat_vector)){
    vector <- c(vector, seurat_vector[[i]])
}
# This will be used to give unique identifiers to cells from each object
object_names <- names(imported_objects)
if (is.null(object_names)) {
  object_names <- paste0("Object", seq_along(imported_objects))
}

# Now, we'll merge the objects

merged_seurat <- merge(seurat_vector[[1]], y = vector, 
                        add.cell.ids = object_names, 
                        project = config$seurat_integration$project_name)
 
head(colnames(merged_seurat))
```
# split layers
```{r split_layers}
merged_seurat[["RNA"]] <- split(merged_seurat[["RNA"]], f = merged_seurat$orig.ident)
merged_seurat
```
# feature selection, scale, dimensionality reduction on combined data
```{r feat_select}
merged_seurat <- feature_selection(merged_seurat, "integration")
```
```{r scale}
# scale data
merged_seurat<- scale_data(merged_seurat, output, "integration")
```
```{r run_dim_reduction}
# run PCA
merged_seurat<- run_and_visualize_pca(merged_seurat, output, "integration")
# run UMAP
merged_seurat<- run_umap(merged_seurat, output, "integration")
```

# integrate data
```{r integrate_data}
integration_type <- config$seurat_integration$integration_type
if(integration_type == "cca"){
  merged_seurat <- IntegrateLayers(
    object = merged_seurat, method = CCAIntegration,
    orig.reduction = "pca", new.reduction = "integrated.cca",
    k.weight = 96,
    verbose = FALSE
  )
} else if(integration_type == "rpca"){
  merged_seurat <- IntegrateLayers(
    object = merged_seurat, method = RPCAIntegration,
    orig.reduction = "pca", new.reduction = "integrated.rpca",
    verbose = FALSE
  )
} else if(integration_type == "harmony"){
  merged_seurat <- IntegrateLayers(
    object = merged_seurat, method = HarmonyIntegration,
    orig.reduction = "pca", new.reduction = "harmony",
    verbose = FALSE)
} else if(integration_type == "mnn"){
  merged_seurat <- IntegrateLayers(
    object = merged_seurat, method = FastMNNIntegration,
    new.reduction = "integrated.mnn",
    verbose = FALSE)
} else if(integration_type == "scvi"){
  merged_seurat <- IntegrateLayers(
    object = merged_seurat, method = scVIIntegration,
    new.reduction = "integrated.scvi",
    conda_env = "../miniconda3/envs/scvi-env", verbose = FALSE
  )
} else {
  print("Need to specify integration type (cca, rpca, harmony, mnn, or scvi)")
}
```
# cluster integrated data and run umap again
```{r run_clustering}
# run clustering
## Note: you must have the reduction in the config file set to new.reduction from above in order for this to work
merged_seurat <- perform_clustering(merged_seurat, output, "integration")
```
```{r umap}
# run umap again to visualize clusters in integratied space
cluster_name <- config$seurat_integration$perform_clustering$cluster_name
if(integration_type == "cca"){
  merged_seurat <- RunUMAP(merged_seurat, reduction = "integrated.cca", 
                        dims = 1:30, reduction.name = "umap.cca")
  # visualize
  p1 <- DimPlot(merged_seurat,reduction = "umap.cca",
    group.by = c("orig.ident", "CellType", cluster_name),
    combine = FALSE, label.size = 2
  )
  pdf(paste0(output,"umap_merged_cca.pdf"))
  print(p1)
  dev.off()
} else if(integration_type == "rpca"){
  merged_seurat <- RunUMAP(merged_seurat, reduction = "integrated.rpca", 
                        dims = 1:30, reduction.name = "umap.rpca")
  # visualize
  p1 <- DimPlot(merged_seurat,reduction = "umap.rpca",
    group.by = c("orig.ident", "CellType", cluster_name),
    combine = FALSE, label.size = 2
  )
  pdf(paste0(output,"umap_merged_rpca.pdf"))
  print(p1)
  dev.off()
} else if(integration_type == "harmony"){
  merged_seurat <- RunUMAP(merged_seurat, reduction = "harmony", 
                        dims = 1:30, reduction.name = "umap.harmony")
  # visualize
  p1 <- DimPlot(merged_seurat,reduction = "umap.harmony",
    group.by = c("orig.ident", "CellType", cluster_name),
    combine = FALSE, label.size = 2
  )
  pdf(paste0(output,"umap_merged_harmony.pdf"))
  print(p1)
  dev.off()
} else if(integration_type == "mnn"){
  merged_seurat <- RunUMAP(merged_seurat, reduction = "integrated.mnn", 
                        dims = 1:30, reduction.name = "umap.mnn")
  # visualize
  p1 <- DimPlot(merged_seurat,reduction = "umap.mnn",
    group.by = c("orig.ident", "CellType", cluster_name),
    combine = FALSE, label.size = 2
  )
  pdf(paste0(output,"umap_merged_mnn.pdf"))
  print(p1)
  dev.off()
} else if(integration_type == "scvi"){
  merged_seurat <- RunUMAP(merged_seurat, reduction = "integrated.scvi", 
                        dims = 1:30, reduction.name = "umap.scvi")
  # visualize
  p1 <- DimPlot(merged_seurat,reduction = "umap.scvi",
    group.by = c("orig.ident", "CellType", cluster_name),
    combine = FALSE, label.size = 2
  )
  pdf(paste0(output,"umap_merged_scvi.pdf"))
  print(p1)
  dev.off()
}
```
# save
```{r save_data}
saveRDS(merged_seurat, file= paste0(output,"merged_seurat.rds"))
```
```{r load_data}
merged_seurat <- readRDS(file = paste0(output,"merged_seurat.rds"))
merged_seurat
```

# join layers
```{r join}
merged_seurat <- JoinLayers(merged_seurat)
merged_seurat
# convert to v3 object
merged_seurat[["RNA3"]] <- as(object = merged_seurat[["RNA"]], Class = "Assay")
```
# now perform DE analysis
```{r de_analysis}
# run score and plot markers
annot_df <- score_and_plot_markers(merged_seurat, output, "integration")
```
# annotate
```{r annotate}
if (config$seurat_integration$score_and_plot_markers$known_markers) {
    new_df_ordered <- annot_df[order(as.numeric(annot_df$Cluster)), ]
    # Get new cluster names ordered by cluster number
    new_cluster_ids <- new_df_ordered$Cell.type
    merged_seurat <- annotate_clusters_and_save(merged_seurat, new_cluster_ids, output, "integration")
    # return labeled object
    return(merged_seurat) # labeled_seurat_obj
  } else {
    # If no known markers scoring and plotting, return the clustered object only
    return(merged_seurat)
  }
```
# annotate with clustifyr
```{r clustifyr}
# convert to single cell experiment
SCE <- as.SingleCellExperiment(merged_seurat)
# run clustifyr
annotate_with_clustifyR(merged_seurat, SCE, output)
```
# save session info
```{r sessioninfo}
writeLines(capture.output(sessionInfo()), paste0(output,"sessionInfo.txt"))
```